// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Model;

#nullable disable

namespace StarWars.Migrations
{
    [DbContext(typeof(StarWarsDbContext))]
    [Migration("20230419090327_isDeadRound")]
    partial class isDeadRound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StarWars.Model.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("StarWars.Model.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AttackerId")
                        .HasColumnType("int");

                    b.Property<int>("DefenderId")
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDead")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("GameId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("StarWars.Model.Soldier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Soldiers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Soldier");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StarWars.Model.Empire", b =>
                {
                    b.HasBaseType("StarWars.Model.Soldier");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("GameId1");

                    b.ToTable("Soldiers", t =>
                        {
                            t.Property("GameId1")
                                .HasColumnName("Empire_GameId1");

                            t.Property("Name")
                                .HasColumnName("Empire_Name");
                        });

                    b.HasDiscriminator().HasValue("Empire");
                });

            modelBuilder.Entity("StarWars.Model.Rebel", b =>
                {
                    b.HasBaseType("StarWars.Model.Soldier");

                    b.Property<int?>("GameId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("GameId1");

                    b.HasDiscriminator().HasValue("Rebel");
                });

            modelBuilder.Entity("StarWars.Model.Round", b =>
                {
                    b.HasOne("StarWars.Model.Soldier", "Attacker")
                        .WithMany()
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Model.Soldier", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Model.Game", null)
                        .WithMany("Rounds")
                        .HasForeignKey("GameId");

                    b.Navigation("Attacker");

                    b.Navigation("Defender");
                });

            modelBuilder.Entity("StarWars.Model.Soldier", b =>
                {
                    b.HasOne("StarWars.Model.Game", null)
                        .WithMany("Soldiers")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("StarWars.Model.Empire", b =>
                {
                    b.HasOne("StarWars.Model.Game", null)
                        .WithMany("Empires")
                        .HasForeignKey("GameId1");
                });

            modelBuilder.Entity("StarWars.Model.Rebel", b =>
                {
                    b.HasOne("StarWars.Model.Game", null)
                        .WithMany("Rebels")
                        .HasForeignKey("GameId1");
                });

            modelBuilder.Entity("StarWars.Model.Game", b =>
                {
                    b.Navigation("Empires");

                    b.Navigation("Rebels");

                    b.Navigation("Rounds");

                    b.Navigation("Soldiers");
                });
#pragma warning restore 612, 618
        }
    }
}
